image: python:3.8.8

docs:
  script:
    - pip install mkdocs-material
    - mkdocs build --strict --verbose
  artifacts:
    paths:
      - public
  only:
    # only run this CI pipeline on master
    refs:
      - master